version: "3.8"

services:
  mobidic-db:
    image: mysql:8.0
    container_name: mobidic-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - mobidic-net

  mobidic-be:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
    container_name: mobidic-be
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mobidic-db:
        condition: service_healthy
    networks:
      - mobidic-net

  mobidic-redis:
    image: redis:7-alpine
    container_name: mobidic-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - mobidic-net

networks:
  mobidic-net:
    external: true

volumes:
  certbot-etc:
  certbot-var:
  db-data:
  redis-data: