spring:
  config:
    import:
      - optional:classpath:application-storage-test.yml
      - optional:classpath:application-external-test.yml
      - optional:classpath:application-security-test.yml

server:
  port: 8080

oauth2:
  callback-url:
    frontend:
      kakao:
        frontend-callback-url: test
        android-callback-url: test
        dev:
          frontend-callback-url: test