whisper:
  flask-server-url: ${FLASK_HOST}

oauth2:
  secrets:
    kakao:
      rest-api-key: ${KAKAO_REST_API_KEY}
      client-secret: ${KAKAO_CLIENT_SECRET}
      dev:
        backend-callback-url: ${KAKAO_DEV_BACKEND_CALLBACK_URL}
